version: '3'
services:
  front:
    container_name: front
    build: ./docker/front
    ports:
      - 5173:5173
    volumes:
      - ./front:/front
    stdin_open: true
    tty: true
    environment:
      - TZ=Asia/Tokyo
    command: npm run dev

  api:
    container_name: api
    build: ./docker/api
    ports:
      - 3000:3000
    volumes:
      - ./api:/api
    stdin_open: true
    tty: true
    environment:
      - TZ=Asia/Tokyo
    command: npm run nodemon
    # depends_on:
    #   - mysql

  db:
    container_name: db
    build: ./docker/db
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db/conf/my.cnf:/etc/mysql/conf.d/my.cnfs
      - ./db/mysql:/var/lib/mysql

volumes:
  mysql-data:

