version: '3'
services:
  front:
    container_name: front
    build:
      context: .
      dockerfile: ./docker/front/Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./front:/front
    stdin_open: true
    tty: true
    env_file: .env
    command: npm run dev
    networks:
      - default

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - ./api:/api
    stdin_open: true
    tty: true
    environment:
      - MYSQL_HOST=db
    env_file: .env
    command: npm run nodemon
    expose:
      - 3001
    depends_on:
      - db
    networks:
      - default

  db:
    container_name: db
    build: ./docker/db
    image: mysql:8.0
    ports:
      - 3306:3306
    env_file: .env
    volumes:
      - ./db/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysql-data:/var/lib/mysql
    networks:
      - default

networks:
  default:

volumes:
  mysql-data:

